- name: delete borg backup for {{ backup_server }}:{{ backup_port }}/{{ target_dir }}\{{ backup_name }}
  expect:
    command: borg delete ssh://{{backup_user}}@{{ backup_server }}:{{ backup_port }}/{{ target_dir }}\{{ backup_name }}
    responses:
      passphrase:
      - "{{ backup_encryption_key }}"
      DELETE:
      - "YES"